/**
 * Import script — reviews scraped jobs and adds approved ones to the dataset.
 *
 * Reads the latest scraped JSON files from backend/data/scraped/,
 * deduplicates against existing postings, and writes approved jobs
 * to backend/src/data/scraped-postings.ts for the seed pipeline.
 *
 * Usage:
 *   npx tsx src/scraper/import-scraped.ts           # Interactive review
 *   npx tsx src/scraper/import-scraped.ts --auto     # Auto-approve all
 *   npx tsx src/scraper/import-scraped.ts --source bayt  # Only import from Bayt
 *   npx tsx src/scraper/import-scraped.ts --dry-run  # Preview without writing
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { ScraperManager } from './scraper-manager';
import { ScrapedJob } from './types';
import { JobPostingData } from '../types';

const SCRAPED_POSTINGS_FILE = path.resolve(__dirname, '../data/scraped-postings.ts');

function parseArgs(): { auto: boolean; source?: string; dryRun: boolean } {
  const args = process.argv.slice(2);
  let auto = false;
  let source: string | undefined;
  let dryRun = false;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--auto':
        auto = true;
        break;
      case '--source':
        source = args[++i];
        break;
      case '--dry-run':
        dryRun = true;
        break;
    }
  }

  return { auto, source, dryRun };
}

/** Prompt the user for a yes/no answer. */
async function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() !== 'n');
    });
  });
}

/** Generate the TypeScript source file for scraped postings. */
function generateScrapedPostingsFile(jobs: JobPostingData[]): string {
  const lines = [
    '/**',
    ' * Scraped job postings imported from web scraping.',
    ' *',
    ' * These are REAL postings scraped from public job boards.',
    ' * source_label is always "real" and source_name indicates the origin site.',
    ' *',
    ` * Last import: ${new Date().toISOString().split('T')[0]}`,
    ` * Total imported: ${jobs.length}`,
    ' *',
    ' * Auto-generated by: npx tsx src/scraper/import-scraped.ts',
    ' * Do not edit manually — re-run the import script instead.',
    ' */',
    '',
    "import { JobPostingData } from '../types';",
    '',
    'export const SCRAPED_POSTINGS: JobPostingData[] = ',
    JSON.stringify(jobs, null, 2).replace(/"([^"]+)":/g, '  "$1":') + ';',
    '',
  ];

  return lines.join('\n');
}

/** Load existing scraped postings if the file exists. */
function loadExistingScrapedPostings(): JobPostingData[] {
  if (!fs.existsSync(SCRAPED_POSTINGS_FILE)) return [];

  // Parse the existing file to extract the array
  const content = fs.readFileSync(SCRAPED_POSTINGS_FILE, 'utf-8');
  const match = content.match(/export const SCRAPED_POSTINGS: JobPostingData\[\] = (\[[\s\S]*?\]);/);
  if (!match) return [];

  try {
    return JSON.parse(match[1]);
  } catch {
    return [];
  }
}

async function main(): Promise<void> {
  const { auto, source, dryRun } = parseArgs();

  console.log('╔══════════════════════════════════════════════════╗');
  console.log('║   SkillBridge — Import Scraped Postings         ║');
  console.log('╚══════════════════════════════════════════════════╝\n');

  // Load scraped data
  const scrapedJobs = ScraperManager.loadLatest(source);
  if (scrapedJobs.length === 0) {
    console.log('  No scraped jobs found in backend/data/scraped/.');
    console.log('  Run the scraper first: npx tsx src/scraper/run-scraper.ts\n');
    return;
  }

  console.log(`  Found ${scrapedJobs.length} scraped job(s)${source ? ` from ${source}` : ''}.\n`);

  // Deduplicate against existing
  const manager = new ScraperManager();
  const { newJobs, duplicates } = manager.deduplicateAgainstExisting(scrapedJobs);

  if (duplicates.length > 0) {
    console.log(`  ⚠️  ${duplicates.length} duplicate(s) removed (already in dataset).`);
  }

  if (newJobs.length === 0) {
    console.log('  No new jobs to import. All scraped jobs are already in the dataset.\n');
    return;
  }

  console.log(`  ${newJobs.length} new job(s) available for import:\n`);

  // Review and approve
  const approved: ScrapedJob[] = [];

  for (let i = 0; i < newJobs.length; i++) {
    const job = newJobs[i];
    console.log(`  ── Job ${i + 1}/${newJobs.length} ──────────────────────`);
    console.log(`    Title:    ${job.title}`);
    console.log(`    Company:  ${job.company}`);
    console.log(`    Location: ${job.location}`);
    console.log(`    Source:   ${job.source_name}`);
    console.log(`    Date:     ${job.date_posted ?? 'Unknown'}`);
    console.log(`    URL:      ${job.url}`);
    console.log(`    Desc:     ${job.description.substring(0, 150)}…`);
    console.log('');

    if (auto) {
      approved.push(job);
      console.log(`    ✅ Auto-approved.\n`);
    } else {
      const accept = await confirm('    Import this job? [Y/n] ');
      if (accept) {
        approved.push(job);
        console.log(`    ✅ Approved.\n`);
      } else {
        console.log(`    ⏭️  Skipped.\n`);
      }
    }
  }

  if (approved.length === 0) {
    console.log('  No jobs approved for import.\n');
    return;
  }

  // Convert to JobPostingData
  const converted = ScraperManager.toJobPostingData(approved);

  // Merge with existing scraped postings
  const existing = loadExistingScrapedPostings();
  const merged = [...existing, ...converted];

  if (dryRun) {
    console.log(`\n  🔍 DRY RUN: Would import ${approved.length} job(s).`);
    console.log(`  Total scraped postings would be: ${merged.length}`);
    console.log('  No files were modified.\n');
    return;
  }

  // Write the scraped-postings.ts file
  const fileContent = generateScrapedPostingsFile(merged);
  fs.writeFileSync(SCRAPED_POSTINGS_FILE, fileContent, 'utf-8');

  console.log(`\n  ✅ Imported ${approved.length} new job(s).`);
  console.log(`  Total scraped postings: ${merged.length}`);
  console.log(`  Written to: ${path.relative(process.cwd(), SCRAPED_POSTINGS_FILE)}`);
  console.log(`\n  Next: run 'npm run seed --workspace=backend' to rebuild the database.\n`);
}

main().catch(err => {
  console.error(`\n❌ Import error: ${err.message}`);
  process.exit(1);
});
